### ISSUE TITLE
Could not pass event "cn.nukkit.event.entity.EntitySpawnEvent" to "AreaProtection v1.1.0"

### ISSUE THREAD

**Issue by jrodr10** [SchdowNVIDIA/AreaProtection#1]
22:06:31 [FATAL] Could not pass event "cn.nukkit.event.entity.EntitySpawnEvent" to "AreaProtection v1.1.0": null on net.llamagames.AreaP
rotection.listener.EntityListener
22:06:31 [ERROR] Throwing
cn.nukkit.utils.EventException: null
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.entity.Entity.init(Entity.java:475) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.entity.Entity.<init>(Entity.java:356) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.entity.item.EntityItem.<init>(EntityItem.java:27) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.level.Level.dropItem(Level.java:1760) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.level.Level.dropItem(Level.java:1728) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.level.Level.dropItem(Level.java:1724) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.level.Level.dropItem(Level.java:1720) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.entity.item.EntityMinecartAbstract.dropItem(EntityMinecartAbstract.java:258) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.entity.item.EntityMinecartAbstract.kill(EntityMinecartAbstract.java:266) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.entity.Entity.setHealth(Entity.java:1039) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.entity.Entity.attack(Entity.java:1000) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.entity.item.EntityVehicle.attack(EntityVehicle.java:112) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.entity.item.EntityMinecartAbstract.attack(EntityMinecartAbstract.java:247) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:3132) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]
        at cn.nukkit.network.Network.processPackets(Network.java:196) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.Network.processBatch(Network.java:179) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:2075) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source) ~[?:?]
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.Network.processInterfaces(Network.java:80) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tick(Server.java:1124) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:903) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.start(Server.java:880) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:565) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) ~[nukkit-1.0-SNAPSHOT.jar:?]
Caused by: cn.nukkit.utils.EventException: Event is not Cancellable
        at cn.nukkit.event.Event.setCancelled(Event.java:46) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at net.llamagames.AreaProtection.listener.EntityListener.onMobSpawn(EntityListener.java:28) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor46.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[nukkit-1.0-SNAPSHOT.jar:?]
        ... 31 more

**Comment by jrodr10** [comment]
Thank you
